########################
# ______ ________  ___ #
# | ___ \_   _|  \/  | #
# | |_/ / | | | .  . | #
# | ___ \ | | | |\/| | #
# | |_/ / | | | |  | | #
# \____/  \_/ \_|  |_/ #
#                      #
########################

[flags]
avg_cpu = true
hide_avg_cpu = true

# Temperature is one of:
temperature_type = "c"

# Use basic mode
basic = true

rate = 1000
left_legend = true
current_usage = false
group_processes = false
case_sensitive = false
whole_word = false
regex = true
default_widget_type = "cpu"
default_widget_count = 1

network_use_log = true
disable_click = false
hide_table_gap = false

# Override layout default widget
default_widget_type = "proc"
default_wi/dget_count = 1

# Show tree mode by default in the processes widget.
tree = false

[colors]
table_header_color="LightYellow"

cpu_core_colors=["Cyan", "Green", "Blue", "Magenta"]

graph_color="Gray"
high_battery_color="cyan"
medium_battery_color="yellow"
low_battery_color="Red"

ram_color="LightBlue"


# Layout - layouts follow a pattern like this:
[[row]] represents a row in the application.
[[row.child]] represents either a widget or a column.
[[row.child.child]] represents a widget.

# All widgets must have the type value set to one of ["cpu", "mem", "proc", "net", "temp", "disk", "empty"].
# All layout components have a ratio value - if this is not set, then it defaults to 1.
# The default widget layout:
[[row]]
    ratio=30
    [[row.child]]
        type="cpu"
[[row]]
    ratio=40
    [[row.child]]
        ratio=4
        type="mem"
    [[row.child]]
        ratio=3
        [[row.child.child]]
            type="temp"
        [[row.child.child]]
            type="disk"
[[row]]
    ratio=30
    [[row.child]]
        type="net"
    [[row.child]]
        type="proc"
        default=true
