#!/bin/sh

# Frenzy's
# BSPWM


# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# wallpaper
feh --bg-tile ~/Pictures/wallpapers/Monochrome/pikaWall_III.png

# Viva el spanish!!!
setxkbmap -layout us -variant altgr-intl

# panel
zsh ~/.config/polybar/launch.sh

# Set some bsp specific stuff
bspc monitor -d I II III IV V VI

# When I have my other (imaginary) monitor
# Find out names with arandr or xrandr
#bspc monitor HDMI1 -d I II III

# Set Xrandr or something
xset r rate 250 40

# Gap n border
bspc config window_gap 16
bspc config border_width 20

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true


bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


# Stolen form Gk, because I'm too stupid to actually learn how to use chwb2
outer='0x1b1b23'   # outer
inner1='0x4c5664'  # focused
inner2='0x292936'  # normal

targets() {
	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen
	esac | grep -iv "$v"
}

draw() { chwb2 -I "$inner" -O "$outer" -i "2" -o "9" $* |:; }

# initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
	while read -r _; do
		v=$(echo $(xdo id -N Firefox))
		v=${v// /\\|}
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw "$(targets focused)"
		inner=$inner2 draw "$(targets  normal)"
	done

