#!/bin/sh

# Frenzy's
# BSPWM

# set root pointer
xsetroot -cursor_name left_ptr

# Fix BSPWM bug with Jetbrains App (fucking soydev)
export _JAVA_AWT_WM_NONREPARENTING=1
bspc set wm_name LG3D

bspc config pointer_modifier mod1

# panel
tint2 &

sh ~/.scripts/notification/hello.sh &

# Wallpaper
feh --bg-fill $HOME/Pictures/wallpapers/Tea\ And\ Coffee/alex-padurariu-3.jpg

# key bindings
sxhkd &

# compositor
picom &

# Mice bindings
#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

#   Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

#   Mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner

# Viva el spanish!!!
setxkbmap -layout us -variant altgr-intl

# Fuck CapsLock, all my homies hate CapsLock
setxkbmap -option caps:swapescape

# Fire eww Daemon
~/eww/target/release/eww daemon &

# panel
zsh ~/.config/polybar/launch.sh

# Set some bsp specific stuff
bspc monitor -d I II III IV V VI

# When I have my other (imaginary) monitor
# Find out names with arandr or xrandr
#bspc monitor HDMI1 -d I II III

# Set Xrandr or something
xset r rate 250 40

bspc rule -a Alacritty rectangle=780x460+0+0 center=true

# Gap n border

bspc config window_gap 16
bspc config border_width 20


bspc config split_ratio 0.64
bspc config borderless_monocle true
bspc config gapless_monocle true


bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


# Stolen form Gk, because I'm too stupid to actually learn how to use chwb2
outer='0x20202A'   # outer
inner1='0x414560'  # focused
inner2='0x2c2e3e'  # normal

targets() {
	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen
	esac | grep -iv "$v"
}

draw() { chwb2 -I "$inner" -O "$outer" -i "2" -o "9" $* |:; }

# initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
	while read -r _; do
		v=$(echo $(xdo id -N Firefox))
		v=${v// /\\|}
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw "$(targets focused)"
		inner=$inner2 draw "$(targets  normal)"
	done

